# Generated by Django 2.0 on 2020-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键自增')),
                ('uid', models.IntegerField(verbose_name='用户id')),
                ('rid', models.IntegerField(verbose_name='角色id')),
            ],
            options={
                'db_table': 'User_Role',
            },
        ),
    ]
